core_website/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'core_website'

urlpatterns = [
    path('', views.apresentacao, name='apresentacao'),
    path('cadastrar-se/', views.cadastro_novo_negocio, name='cadastro_novo_negocio'),
    path('accounts/login/', views.login, name='login'),
    path('login/sucesso/', views.login_view, name='login_sucesso'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('sucesso/', views.sucesso, name='sucesso'),
]

core_website/models.py
from django.db import models

# Create your models here.

core_website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from core_cadastros.models import CustomUser, Enterprise

class EnterpriseForm(forms.ModelForm):
    class Meta:
        model = Enterprise
        fields = ['tipo', 'nome', 'id_nacional', 'telefone', 'email', 'address', 'cnpj']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

class CadastroForm(forms.Form):
    tipo = forms.CharField(widget=forms.HiddenInput())
    nome = forms.CharField(max_length=100, required=True)
    id_nacional = forms.CharField(max_length=18, required=True)  # CPF ou CNPJ
    telefone = forms.CharField(max_length=15, required=True)
    email = forms.EmailField(required=True)
    senha1 = forms.CharField(widget=forms.PasswordInput(), required=True)
    senha2 = forms.CharField(widget=forms.PasswordInput(), required=True)

core_website/views.py
# C:\Users\gusta\OneDrive\Área de Trabalho\Neuron_Hub\neuron_hub\core_website\views.py

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django_tenants.utils import schema_context
from core_tenants.models import Tenant, Domain
from core_cadastros.models import CustomUser, Enterprise
from .forms import CadastroForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.db import connection

def cadastro_novo_negocio(request):
    email_exists = False
    id_nacional_exists = False
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            tipo = form.cleaned_data['tipo']
            nome = form.cleaned_data['nome']
            id_nacional = form.cleaned_data['id_nacional']
            telefone = form.cleaned_data['telefone']
            email = form.cleaned_data['email']
            senha1 = form.cleaned_data['senha1']
            senha2 = form.cleaned_data['senha2']

            if senha1 != senha2:
                messages.error(request, "As senhas não coincidem.")
                return render(request, 'core_website/cadastrar.html', {'form': form})

            if CustomUser.objects.filter(username=email).exists():
                email_exists = True
                return render(request, 'core_website/cadastrar.html', {'form': form, 'email_exists': email_exists})

            if Enterprise.objects.filter(id_nacional=id_nacional).exists():
                id_nacional_exists = True
                return render(request, 'core_website/cadastrar.html', {'form': form, 'idnacional_exists': id_nacional_exists})

            enterprise = Enterprise.objects.create(
                tipo=tipo,
                nome=nome,
                id_nacional=id_nacional,
                telefone=telefone,
                email=email,
                senha=senha1
            )
            tenant = Tenant.objects.create(
                name=nome,
                client=enterprise
            )
            tenant.save() 

            user = CustomUser.objects.create_user(username=email, email=email, password=senha1, enterprise=enterprise, tenant=tenant, nome=nome)

            # Cria um domínio para o tenant
            domain = Domain.objects.create(
                domain=f'{tenant.schema_name}.neuron.com',
                tenant=tenant,
                is_primary=True
            )

            # Criar o schema
            with schema_context(tenant.schema_name):
                pass

            messages.success(request, "Cadastro realizado com sucesso!")
            return redirect('core_website:sucesso')
        else:
            messages.error(request, "Por favor, corrija os erros abaixo.")
    else:
        form = CadastroForm()

    return render(request, 'core_website/cadastrar.html', {'form': form, 'email_exists': email_exists, 'idnacional_exists': id_nacional_exists})

def sucesso(request):
    return render(request, 'core_website/cadastro_sucesso.html')

def apresentacao(request):
    return render(request, 'core_website/apresentacao.html')

def login(request):
    return render(request, 'core_website/login.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)  # Use auth_login para evitar conflito de nome
            schema_name = user.tenant.schema_name
            redirect_url = reverse('sis_inicial:inicio', args=[schema_name])
            return redirect(redirect_url)
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    # Defina o esquema para público antes de fazer logout
    connection.set_schema_to_public()
    auth_logout(request)
    return redirect(reverse('core_website:login'))

core_website/templates/core_website/apresentacao.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/inicial.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            font-family: century gothic;
            background-color: #f2f2f2;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            flex-direction: column;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <h1 style="margin-left: 5%;">Neuron Hub</h1>
        <div class="options">
            <a style="background-color: #00BFFF;" href="{% url 'core_website:cadastro_novo_negocio' %}">Cadastrar</a>
            <a style="color: rgb(70,70,70);" href="{% url 'core_website:login' %}">Entrar</a>
        </div>
    </div>
    <div class="image-container">
        <img src="{% static 'img/imagem_2.jpg' %}">
        <div class="overlay-text">
            <h1>Construindo conexões seguras,</h1>
            <h1>impulsionando negócios com inteligência.</h1>
        </div>
    </div>
</body>
</html>

core_website/templates/core_website/cadastrar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/inicial.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            font-family: century gothic;
            background-color: #f2f2f2;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            flex-direction: column;
        }
        .popup {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: white;
            border: 1px solid #ccc;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            z-index: 1000;
        }
        .popup-overlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.5);
            z-index: 999;
        }
    </style>
</head>
<body>
    <div class="navbar" style="box-shadow: 10px 10px 10px rgba(0,0,0,0.2);">
        <a href="{% url 'core_website:apresentacao' %}" style="width: 20%;height: 100%;display: flex;align-items: center;justify-content: center;text-decoration: none;"><h1 style="margin-left: 5%;">Neuron Hub</h1></a>
    </div>
    <form method="post" class="form_inicial" action="{% url 'core_website:cadastro_novo_negocio' %}">
        {% csrf_token %}
        <h2>Cadastro de Novo Negócio</h2>
        <p id="subtitulo1">Escolha o tipo do seu negócio</p>
        <div class="slider-container"> 
            <div class="slide active" id="slide1">
                <div class="btn_inicial_linha">
                    <button type="button" id="bt_fisica" onclick="mudarSlideInicial(2)">Pessoa Física</button>
                    <button type="button" id="bt_juridica" onclick="mudarSlideInicial(2)">Pessoa Jurídica</button>
                </div>
            </div>
            <div class="slide" id="slide2" style="height: 70%;">
                <div class="primeiro_cadastro">
                    {% if form.errors %}
                        <div class="errorlist">
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    <li><strong>{{ field }}</strong>: {{ errors|join:", " }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="conteudo_linha">
                        <label>Tipo:</label>
                        <input type="text" name="tipo" id="tipo_negocio" style="color: rgb(70,70,70);" value="{{ form.tipo.value|default_if_none:'' }}" readonly>
                    </div>
                    <div class="conteudo_linha">
                        <label>Nome completo:</label>
                        <input type="text" name="nome" id="nome" required autocomplete="off" placeholder="Nome completo" value="{{ form.nome.value|default_if_none:'' }}">
                    </div>
                    <div class="conteudo_linha">
                        <label id="label_cpf">CPF:</label>
                        <label id="label_cnpj" style="display: none;">CNPJ:</label>
                        <input type="text" name="id_nacional" id="id_nacional" required autocomplete="off" value="{{ form.id_nacional.value|default_if_none:'' }}">
                    </div>
                    <div class="conteudo_linha">
                        <label>Telefone:</label>
                        <input type="text" name="telefone" id="telefone" required autocomplete="off" placeholder="Telefone" value="{{ form.telefone.value|default_if_none:'' }}">
                    </div>
                    <div class="conteudo_linha">
                        <label>Email:</label>
                        <input type="email" name="email" id="email" required autocomplete="off" placeholder="Email" value="{{ form.email.value|default_if_none:'' }}">
                    </div>
                    <div class="conteudo_linha">
                        <label>Senha:</label>
                        <input type="password" name="senha1" id="senha1" required autocomplete="off" placeholder="Senha">
                    </div>
                    <div class="conteudo_linha">
                        <label>Confirme a senha:</label>
                        <input type="password" name="senha2" id="senha2" required autocomplete="off" placeholder="Confirme a senha">
                    </div>
                </div>
            </div>
            <div class="linha_btn">
                <button id="volta_slide_inicial" type="button" onclick="mudarSlideInicial(1)">Voltar</button>
                <button type="submit">Cadastrar</button>
            </div>
        </div>
    </form>

    <!-- Pop-up de Erro -->
    <div class="popup-overlay" id="popup-overlay"></div>
    <div class="popup" id="popup">
        <p>Este e-mail já está cadastrado!</p>
        <button onclick="fecharPopup()">Fechar</button>
        <button onclick="login()">login</button>
    </div>

    <div class="popup-overlay" id="popup-overlay"></div>
    <div class="popup" id="popup">
        <p>CPF/CNPJ já está cadastrado!</p>
        <button onclick="fecharPopup()">Fechar</button>
        <button onclick="login()">login</button>
    </div>

    <script>
        var emailExists = "{{ email_exists|yesno:'true,false' }}";
        var idnacionalexists = "{{ idnacional_exists|yesno:'true,false' }}";

        window.onload = function() {
            var inputs = document.querySelectorAll('input');
            inputs.forEach(function(input) {
                input.setAttribute('autocomplete', 'off');
            });

            if (emailExists === "true") {
                document.getElementById('popup-overlay').style.display = 'block';
                document.getElementById('popup').style.display = 'block';
            }

            if (idnacionalexists === "true") {
                document.getElementById('popup-overlay').style.display = 'block';
                document.getElementById('popup').style.display = 'block';
            }
            
        };

        function login() {
            window.location.href = "{% url 'core_website:login' %}";
        }

        function fecharPopup() {
            document.getElementById('popup-overlay').style.display = 'none';
            document.getElementById('popup').style.display = 'none';
            if (emailExists === "true") {
            mudarSlideInicial(2);
            }
        }
    </script>

    <script src="{% static 'js/mudar_slide.js' %}"></script>
    <script src="{% static 'js/cadastro.js' %}"></script>
    <script src="{% static 'js/cadastro_inicial.js' %}"></script>
</body>
</html>

core_website/templates/core_website/cadastro_sucesso.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/inicial.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            font-family: century gothic;
            background-color: #f2f2f2;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            flex-direction: column;
        }

    </style>
</head>
<body>
    <div class="navbar" style="box-shadow: 10px 10px 10px rgba(0,0,0,0.2);">
        <a href="{% url 'core_website:apresentacao' %}" style="width: 20%;height: 100%;display: flex;align-items: center;justify-content: center;text-decoration: none;"><h1 style="margin-left: 5%;">Neuron Hub</h1></a>
    </div>
    <div class="cadastro_sucesso">
        <h1>Cadastro realizado com sucesso!</h1>
        <p>Clique aqui para fazer o login!</p>
        <a href="{% url 'core_website:login' %}">Login</a>
    </div>
    <script src="{% static 'js/mudar_slide.js' %}"></script>
    <script src="{% static 'js/cadastro.js' %}"></script>
    <script>
        window.onload = function() {
            var inputs = document.querySelectorAll('input');
            inputs.forEach(function(input) {
            input.setAttribute('autocomplete', 'off');
            });
        };
    </script>
</body>
</html>

core_website/templates/core_website/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/inicial.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            font-family: century gothic;
            background-color: #f2f2f2;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            flex-direction: column;
        }
    </style>
</head>
<body>
    <div class="navbar" style="box-shadow: 10px 10px 10px rgba(0,0,0,0.2);">
        <a href="{% url 'core_website:apresentacao' %}" style="width: 20%;height: 100%;display: flex;align-items: center;justify-content: center;text-decoration: none;"><h1 style="margin-left: 5%;">Neuron Hub</h1></a>
    </div>
    <form method="post" class="form_login" action="{% url 'core_website:login_sucesso' %}">
        {% csrf_token %}
        <h2>Faça o login!</h2>
        <p id="subtitulo1">Entre com login e senha</p>
        
        {% if messages %}
            <div class="error">
                <p>Por favor, corrija os seguintes erros:</p>
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        
        <div class="primeiro_cadastro">
            <div class="linha_login">
                <input type="text" name="username" id="username" required placeholder="Email" autocomplete="off">
            </div>
            <div class="linha_login">
                <input type="password" name="password" id="password" required autocomplete="off" placeholder="Senha"> 
            </div>       
            <div class="linha_login">
                <button type="button" onclick="voltarPagina()">Cancelar</button>
                <button type="submit">Entrar</button>
            </div>
        </div>
    </form>
    <script src="{% static 'js/mudar_slide.js' %}"></script>
    <script>
        window.onload = function() {
            var inputs = document.querySelectorAll('input');
            inputs.forEach(function(input) {
                input.setAttribute('autocomplete', 'off');
            });
        };
    </script>
</body>
</html>